config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get '/user' => "user#user"
  get '/add_user' => "user#add_user"
  post '/create_user' => "user#create_user"
  get '/user/edituser/:id' => "user#edit_user", :as => 'user_edit'
  put '/update_user' => "user#update_user", :as =>'user_update'
  delete 'user/deleteuser/:id' => "user#delete_user", :as => 'user_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require 'net/http'
  require 'rest-client'
  require 'json'

    def user
        @message = "Hello, Have a nice day..!"
        @user = User.all
    end

    def create_user
      if request.post?
        @name = params[:name]
        @email = params[:email]
        @address = params[:address]
        puts "#{@name} , #{@email},#{@address}"
        @user = User.new(name: @name, email: @email, address: @address)
        if @user.save
          result = RestClient.post(ENV['ApiUrl'],
          {
            'data': {
             'action': 'user creation',
             'name': @name,
             'email': @email,
             'address': @address
            }
            
          } 
        )
        if result.code == 200
          flash[:success] = "User is created and informed to webook sucessfully!"
         else
          flash[:success] = "User is created and informed to webook !"
        end
        redirect_to '/user'
      end  
     end
    end

    def edit_user
      @user = User.find_by(id: params[:id])

    end 

    def update_user
      @id = params[:id]
      @name = params[:name]
      @email = params[:email]
      @address = params[:address]
      @user = User.find(@id)
      if @user.update(name: @name, email: @email, address: @address)
        result = RestClient.post(ENV['ApiUrl'],
        {
          'data': {
           'action': 'user update',
           'name': @name,
           'email': @email,
           'address': @address
          }
          
        } 
      )
      
      if result.code == 200
        flash[:success] = "User is updated and informed to webook sucessfully!"
       else
        flash[:success] = "User is updated and not informed to webook !"
      end
      redirect_to '/user'
       end
    end

    def delete_user
      @id = params[:id]
      @user = User.find_by(id: @id)
     if @user.destroy
      result = RestClient.post(ENV['ApiUrl'],
      {
        'data': {
         'action': 'user delete',
         'name': @user.name,
         'email': @user.email,
         'address': @user.address
        }
        
      } 
    )
    if result.code == 200
      flash[:success] = "User is deleted and informed to webook sucessfully!"
     else
      flash[:success] = "User is deleted and not informed to webook !"
    end
    redirect_to '/user'
     end
    end

    def add_user
      @user = User.new
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catdigital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script>
      // this function will auto close the flash messages after 3 sec
            function myfn(){
       setTimeout(function() {$("#notice").click() }, 3000);
           console.log("hello i am called from flash notice")
        }
    </script>
  </body>
</html>

app/views/user/add_user.html.erb
 <div class="container">
    <div class= "row">
      <h1 class="ml-1 mt-3 col-md-4">  </h1>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-warning alert-dismissible fade show col-md-6 ml-1 mt-3 float-right"  role="alert">
          <img src onerror='myfn()'>
          <span class="alert-icon"><i class="fas fa-thumbs-down"></i></span>
          <span class="alert-text"><strong>Warning!</strong> <%= message %> </span>
          <button type="button" class="close" id="notice" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
       <h1>A Cat Digital Assignment</h1> 
    <h3> User Create </h3>
    </div>
    <div class="row mt-4">
      <div class="col-md-12">
        <%= form_with(url: "/create_user", method: "post") do |u| %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= u.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Name", class: "form-control form-control-alternative",required: true %>
              </div>
              <div class="form-group">
                <%= u.email_field :email, autocomplete: "email", placeholder: "name@mail.com", class: "form-control form-control-alternative", required: true %>
              </div>
              <div class="form-group">
                <%= u.text_field :address, autocomplete: "address", class: "form-control form-control-alternative", required: true, placeholder: "address" %>
              </div>
             
            </div>
            <div class="col-md-4 text-right">
              <div class="form-group">
                <%= u.submit "Create", class: "btn btn-primary" %>
              </div>
              <div class="mt-2 form-group">
                 <%= link_to 'Back',user_path, class: "btn btn-outline-danger"%>
              </div>
            </div>
          </div>
        </div>
      <% end%>
    </div>
  </div>

app/views/user/edit_user.html.erb
 <div class="container">
 <div class="row mt-4 ">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%> alert-dismissible fade show col-md-6 mt-3" role="alert">
           <img src onerror='myfn()'>
    <button type="button" id="notice" class="btn-close" data-bs-dismiss="alert"></button>
    <strong></strong> <%= message %>
  </div>
      <% end %>
       <div class="row">
    <h1>A Cat Digital Assignment</h1> 
    <h3> User edit </h3>
      <div class="col-md-6">
        <div class="form-group">
          <%= form_with(url: "/update_user", method: "put") do |u| %>
            <input type="text" name="id" class="form-control form-control-alternative" id="exampleFormControlInput1"value="<%= @user.id%>" hidden>
            <input type="text" name="name" class="form-control form-control-alternative" id="exampleFormControlInput1"value="<%= @user.name%>">
          </div>
          <div class="form-group">
            <input type="email" name="email" class="form-control form-control-alternative" id="exampleFormControlInput1"
             value="<%= @user.email%>">
          </div>

           <div class="form-group">
            <input type="text" name="address" class="form-control form-control-alternative" id="exampleFormControlInput1"
             value="<%= @user.address%>">
          </div>
         
        </div>
        <div class="col-md-4 text-right">
          <div class="form-group">
            <%= u.submit "Update", class: "btn btn-primary",style: "width: 80px;" %>
          </div>
          <div class=" mt-2 form-group">
            <%= link_to 'Back',@user, class: "btn btn-outline-danger"%>
          </div>
        </div>
      <% end%>
    </div>
    </div>

app/views/user/user.html.erb
<!-- Main Content -->
<div class="main-content"  style=" background: #f4f5f7; height: 100vh;"  >
  <!-- Container Start -->
  <div class="container">
    <div class="row">
    <h1>A Cat Digital Assignment</h1> 
     <p><%= @message %></p>
      <div class="col-md-3">
        <h1 class="ml-1 mt-3">  <a href="/add_user" class="btn btn-primary btn-sm ml-2 ">Create User</a> </h1>
      </div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%> alert-dismissible fade show col-md-6 mt-3" role="alert">
           <img src onerror='myfn()'>
    <button type="button" id="notice" class="btn-close" data-bs-dismiss="alert"></button>
    <strong></strong> <%= message %>
  </div>
      <% end %>
    </div>
    <!-- Table Start -->
    <!-- Table End -->
    <!-- Dark Table -->
    <div class="row mt-5">
      <div class="col">
        <div class="card bg-default shadow">
          <div class="card-header bg-transparent border-0">
            <h3 class="text-white ">  </h3>
            <%
=begin%>
            <div class="float-right">
              <input class="form-control" type="search" value="Filter" id="example-search-input">
            </div>
            <%
=end%>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-dark table-flush">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Address</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                <% @user.each do |u| %>
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                        </a>
                        <div class="media-body">
                          <span class="mb-0 text-sm"><%= u.name%></span>
                        </div>
                      </div>
                    </th>
                    <td>
                      <%= u.email %>
                    </td>
                    <td>
                      <%= u.address %>
                    </td>

                     <td>
                      
                      
                        <%= link_to 'Edit',user_edit_path(:id => u.id), method: :get, class: "btn btn-warning btn-sm"%> 
                        <%= link_to 'Delete', user_delete_path(:id => u.id), method: :delete, data: { confirm: "Are you sure want to delete user?" },class: "btn btn-danger btn-sm" %>
                     
                    </td>
                   
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- Dark Table End-->
  </div>
  <!-- Container End -->
</div>
<!-- Main Content End -->